name: first

on: push

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Step one of job 1
        uses: actions/checkout@v2
      - name: Step two of job 2
        run: env | sort
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: Step one of job 2
        uses: actions/checkout@v2
      - name: Step two of job 2
        run: "Get-ChildItem Env: Sort-Object Name"

